{
 "title": "Locations and Queries",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "show tag values with key = \"server\""
   },
   {
    "name": "node",
    "label": "Node",
    "query": "show tag values with key = \"node\""
   }
  ]
 },
 "panels": [
  {
   "title": "Queries by Country",
   "type": "geomap",
   "description": "Mean value of queries by country code lookup using client_subnet",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clientcountry" ], "type": "tag" }
     ],
     "measurement": "client_subnet_country",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ($__interval_ms/1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries per Authority",
   "type": "piechart",
   "description": "Distribution of queries based on Regional Internet Registry (RIR) aka authority",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clientauthority" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "client_subnet_authority",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Classifications",
   "type": "piechart",
   "description": "Distribution of query classifications",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "class" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "client_subnet2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "QTYPE vs TLD (top20)",
   "type": "barchart",
   "description": "QTYPE statistics per QNAME TLD, showing top 20 TLDs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tld" ], "type": "tag" },
      { "params": [ "qtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qtype_vs_tld",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "RCODE per IP/NET (top20)",
   "type": "barchart",
   "description": "RCODE statistics per IP/NET for failed quries (rcode != NoError), showing top 20 IP/NETs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clientaddr" ], "type": "tag" },
      { "params": [ "rcode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "client_addr_vs_rcode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "RCODE per QNAME 2nd level domains (top20)",
   "type": "barchart",
   "description": "RCODE statistics per QNAME 2nd level domains for failed quries (rcode != NoError), showing top 20 IP/NETs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "secondld" ], "type": "tag" },
      { "params": [ "rcode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "second_ld_vs_rcode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "RCODE per QNAME 3rd level domains (top20)",
   "type": "barchart",
   "description": "RCODE statistics per QNAME 3rd level domains for failed quries (rcode != NoError), showing top 20 IP/NETs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "thirdld" ], "type": "tag" },
      { "params": [ "rcode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "third_ld_vs_rcode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}