{
 "title": "Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "show tag values with key = \"server\""
   },
   {
    "name": "node",
    "label": "Node",
    "query": "show tag values with key = \"node\""
   }
  ]
 },
 "panels": [
  {
   "title": "libpcap statistics",
   "type": "timeseries",
   "description": "statistics from libpcap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_pcap_stat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pcap_stat" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pcap_stats",
     "query": "SELECT derivative(max(\"value\"), $__interval) FROM \"pcap_stats\" WHERE (\"server\" =~ /^$server$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"pcap_stat\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ($__interval_ms/1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "filtered vs received",
   "type": "timeseries",
   "description": "A stacked graph of packets filtered vs received, can be used to detect problems with libpcap capturing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_pcap_stat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pcap_stat" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pcap_stats",
     "query": "SELECT derivative(max(\"value\"), $__interval) FROM \"pcap_stats\" WHERE (\"server\" =~ /^$server$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"pcap_stat\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "queries",
   "type": "timeseries",
   "description": "queries per second",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "queries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "qtype",
     "query": "SELECT sum(\"value\")  / ($__interval_ms/1000) FROM \"qtype\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ($__interval_ms/1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "responses",
   "type": "timeseries",
   "description": "responses per second",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "responses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rcode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ($__interval_ms/1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "queries vs responses",
   "type": "timeseries",
   "description": "a stacked graph showing the difference between queries and responses",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "queries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "qtype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ($__interval_ms/1000)" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "responses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rcode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ($__interval_ms/1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Failure Rate",
   "type": "timeseries",
   "description": "Total number of RCODEs that is not NoError divided by total number of queries to give a percentage of failure rate\n\nIf you see >100% then either response time is very high or you're receiving fake/spoofed responses, for example cache poisoning attempts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "qtype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "rcode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "rcode", "operator": "!=", "value": "NoError" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    { "expression": "$B / (($A == 0) + $A)", "type": "math" }
   ]
  },
  {
   "title": "RCODEs",
   "type": "piechart",
   "description": "Distribution between RCODEs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rcode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "client_addr_vs_rcode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time log10 buckets",
   "type": "timeseries",
   "description": "Percent based distribution between response time log10 buckets - not number of queries!",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "alias": "$tag_responsetime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "responsetime" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "response_time",
     "query": "SELECT mean(\"value\") FROM \"response_time\" WHERE (\"responsetime\" <> 'internal_errors' AND \"responsetime\" <> 'dropped_queries') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "responsetime", "operator": "<>", "value": "internal_errors" },
      { "condition": "AND", "key": "responsetime", "operator": "<>", "value": "dropped_queries" },
      { "condition": "AND", "key": "responsetime", "operator": "<>", "value": "missing_queries" },
      { "condition": "AND", "key": "responsetime", "operator": "<>", "value": "timeouts" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "DO bit",
   "type": "timeseries",
   "description": "Number of queries with do bit set and it's ratio against the total number of queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "do_bit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "d0", "operator": "=", "value": "set" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qtype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "RD bit",
   "type": "timeseries",
   "description": "Number of queries with rd bit set and it's ratio against the total number of queries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "rd_bit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "rd", "operator": "=", "value": "set" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "qtype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  }
 ]
}